# -*- coding: utf-8 -*-
"""23 Aug 2026 (py conditions and loops).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaWytjbGZu1r4hi07QWcFeK0HslVnK5x

Conditions
"""

age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible.")
else:
    print("You are not eligible.")

age = int(input("Enter your age: "))

if age >= 18:
    nationality = input("Enter your nationality: ")

    if nationality.lower() == "indian":
        print("You are eligible.")
    else:
        print("You are not eligible because of nationality.")
else:
    print("You are not eligible because you are under 18.")

age = int(input("Enter your age: "))

if age >= 18:
    nationality = input("Enter your nationality: ")

    if nationality.lower() == "indian":
        voter_id = input("Do you have a voter ID? (yes/no): ")

        if voter_id.lower() == "yes":
            print("You are eligible to vote.")
        else:
            print("You are not eligible because you do not have a voter ID.")
    else:
        print("You are not eligible because of nationality.")
else:
    print("You are not eligible because you are under 18.")

age = int(input("Enter your age: "))
nationality = input("Enter your nationality: ")
voter_id = input("Do you have a voter ID? (yes/no): ")

if age < 18:
    print("Not eligible: under 18.")
elif nationality.lower() != "indian":
    print("Not eligible: nationality requirement not met.")
elif voter_id.lower() != "yes":
    print("Not eligible: voter ID not available.")
else:
    print("Eligible to vote.")

age = int(input("Enter your age: "))
nationality = input("Enter your nationality: ")
voter_id = input("Do you have a voter ID? (yes/no): ")

if age < 18:
    print("Not eligible: under 18.")
elif nationality.lower() != "indian":
    print("Not eligible: nationality requirement not met.")
elif voter_id.lower() != "yes":
    print("Not eligible: voter ID not available.")
else:
    print("Eligible to vote.")
