# -*- coding: utf-8 -*-
"""23 Aug 2026 (py conditions and loops).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jaWytjbGZu1r4hi07QWcFeK0HslVnK5x

Conditions
"""

age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible.")
else:
    print("You are not eligible.")

age = int(input("Enter your age: "))

if age >= 18:
    nationality = input("Enter your nationality: ")

    if nationality.lower() == "indian":
        print("You are eligible.")
    else:
        print("You are not eligible because of nationality.")
else:
    print("You are not eligible because you are under 18.")

age = int(input("Enter your age: "))

if age >= 18:
    nationality = input("Enter your nationality: ")

    if nationality.lower() == "indian":
        voter_id = input("Do you have a voter ID? (yes/no): ")

        if voter_id.lower() == "yes":
            print("You are eligible to vote.")
        else:
            print("You are not eligible because you do not have a voter ID.")
    else:
        print("You are not eligible because of nationality.")
else:
    print("You are not eligible because you are under 18.")

age = int(input("Enter your age: "))
nationality = input("Enter your nationality: ")
voter_id = input("Do you have a voter ID? (yes/no): ")

if age < 18:
    print("Not eligible: under 18.")
elif nationality.lower() != "indian":
    print("Not eligible: nationality requirement not met.")
elif voter_id.lower() != "yes":
    print("Not eligible: voter ID not available.")
else:
    print("Eligible to vote.")

age = int(input("Enter your age: "))
nationality = input("Enter your nationality: ")
voter_id = input("Do you have a voter ID? (yes/no): ")

if age < 18:
    print("Not eligible: under 18.")
elif nationality.lower() != "indian":
    print("Not eligible: nationality requirement not met.")
elif voter_id.lower() != "yes":
    print("Not eligible: voter ID not available.")
else:
    print("Eligible to vote.")

"""Leap Year condition"""

year = int(input("Enter your age: "))


if year % 400 == 0:
    print("Leap year")
elif (year % 4 == 0) and (year % 100 != 0):
    print("Leap year")
else:
    print("Not a leap year")

"""For loop Examples"""

listofDishes = ["Pasta","Briyani","curdrice","sambar"]

for e in listofDishes:
    print(e)
    print("  ")
    if e == "Briyani":
        print("foudnd Briyani")
        break

listofValues = [1,2,3,4,5,6,7,8,9,10]

for e in listofValues:
    if e % 2: print("even")
    else: print("odd")

print("Think of a number between 1 and 100.")

low = 1
high = 100

while True:
    guess = (low + high) // 2
    print(f"My guess is: {guess}")

    feedback = input("Is it 'high', 'low', or 'correct'? ").lower()

    if feedback == "correct":
        print("Yay! I guessed your number.")
        break
    elif feedback == "high":
        high = guess - 1
    elif feedback == "low":
        low = guess + 1
    else:
        print("Please enter high, low, or correct.")

#EvenOdd
# number % 2 == 0 Even
#listofValues = [1,1,3,5,7,9,1,3,5,2,5,6]
listofValues = [1,1,3,5,7,9,1,3,5]
startOfValue = 0
endOfValue = (len(listofValues)-1)

while(startOfValue <= endOfValue):  # It should be True
 ## I am finding the value from the list which i need to check
  number = listofValues[startOfValue]
  #print(number)

  if number % 2 == 0:
    print(number,"is Even")
    break
  startOfValue= startOfValue + 1
  print("No even number found")

"""Nested Loops"""

for e1 in [1,4]:
  print("sets", e1)